from __future__ import annotations

import re

SENSITIVE_FILE_PATTERNS = [
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "*.kdbx",
    "id_rsa",
    "id_ed25519",
    "credentials",
    "credentials.*",
    "secrets.*",
    "secret.*",
    "*.tfstate",
    "*.tfvars",
    ".npmrc",
    ".pypirc",
    ".netrc",
    ".git-credentials",
    "application.properties",
    "application.yml",
    "application.yaml",
]

RULES = {
    "enumeration": [
        (r"\breaddir(?:Sync)?\b", "strong"),
        (r"\bwalk(?:Dir)?\b", "strong"),
        (r"\bos\.walk\b", "strong"),
        (r"\bfast[-_]?glob\b", "strong"),
        (r"\brecursive\s*[:=]\s*true\b", "strong"),
        (r"\bgit\s+(?:ls-files|rev-list|reflog)\b", "strong"),
        (r"\.git[/\\](?:objects|logs|lfs)", "strong"),
        (r"\bglob(?:Sync)?\b", "weak"),
        (r"\*\*/\*", "weak"),
    ],
    "snapshot": [
        (r"\bworkspaceSnapshot\b", "strong"),
        (r"\brepositorySnapshot\b", "strong"),
        (r"\brepoSnapshot\b", "strong"),
        (r"\bworkspace[-_ ]snapshot\b", "strong"),
        (r"\brepository[-_ ]snapshot\b", "strong"),
        (r"\bcreateWorkspaceSnapshot\b", "strong"),
        (r"\bsnapshotWorkspace\b", "strong"),
        (r"\brepo(?:sitory)?[-_ ]?(?:index|wiki)\b", "strong"),
        (r"\bworkspace[-_ ]?(?:archive|index)\b", "strong"),
        (r"\bsnapshot\b", "weak"),
        (r"\bcheckpoint\b", "weak"),
        (r"\bbaseline\b", "weak"),
        (r"\bmanifest\b", "weak"),
    ],
    "archive": [
        (r"\bzipfile\b", "strong"),
        (r"\btarfile\b", "strong"),
        (r"\barchiver\b", "strong"),
        (r"\bcreateGzip\b", "strong"),
        (r"\bgzipSync\b", "strong"),
        (r"\bgzip\b", "strong"),
        (r"\bdeflate\b", "strong"),
        (r"\bcompress(?:ion|ed)?\b", "weak"),
        (r"\b7z\b", "weak"),
        (r"\btar\b", "weak"),
        (r"\bzip\b", "weak"),
    ],
    "crypto": [
        (r"\bAES[-_ ]?(?:128|192|256)?\b", "strong"),
        (r"\bRSA[-_ ]?(?:OAEP)?\b", "strong"),
        (r"\bcreateCipheriv\b", "strong"),
        (r"\bcrypto\.subtle\b", "strong"),
        (r"\bwrap(?:ped)?Key\b", "strong"),
        (r"\bpublicKey\b", "weak"),
        (r"\bencrypt(?:ion|ed)?\b", "weak"),
    ],
    "upload": [
        (r"\bputObject\b", "strong"),
        (r"\buploadObject\b", "strong"),
        (r"\bmultipartUpload\b", "strong"),
        (r"\baxios\.(?:put|post)\b", "strong"),
        (r"\brequests\.(?:put|post)\b", "strong"),
        (r"\bhttpx\.(?:put|post)\b", "strong"),
        (r"\bcurl\b.*\b(?:PUT|POST)\b", "strong"),
        (r"\bupload(?:File|Blob|Stream|Data)\b", "strong"),
        (r"\bpresigned?\s*url\b", "strong"),
        (r"\bsignedUrl\b", "strong"),
        (r"\bFormData\b", "weak"),
        (r"\bfetch\s*\(", "weak"),
        (r"\bupload\b", "weak"),
    ],
    "object_storage": [
        (r"\baliyun\b", "strong"),
        (r"\balibaba(?:cloud)?\b", "strong"),
        (r"\boss[-_.a-z0-9]*\.aliyuncs\.com\b", "strong"),
        (r"\bamazonaws\.com\b", "strong"),
        (r"\bs3[.-][a-z0-9-]+\.amazonaws\.com\b", "strong"),
        (r"\bstorage\.googleapis\.com\b", "strong"),
        (r"\bblob\.core\.windows\.net\b", "strong"),
        (r"\br2\.cloudflarestorage\.com\b", "strong"),
        (r"\bbackblazeb2\.com\b", "strong"),
        (r"\bdigitaloceanspaces\.com\b", "strong"),
        (r"\bminio\b", "weak"),
    ],
    "retry_queue": [
        (r"\bpending[-_ ]?(?:upload|snapshot|queue)\b", "strong"),
        (r"\bfailureCount\b", "strong"),
        (r"\bmarkAccepted\b", "strong"),
        (r"\blastAccepted\b", "strong"),
        (r"\bqueue(?:Upload|Snapshot)\b", "strong"),
        (r"\bretry\b", "weak"),
        (r"\bbackoff\b", "weak"),
    ],
    "sensitive_mentions": [
        (r"\.env\b", "strong"),
        (r"\.git[/\\](?:objects|logs|lfs|config)", "strong"),
        (r"\bid_rsa\b", "strong"),
        (r"\bid_ed25519\b", "strong"),
        (r"\bapi[-_]?key\b", "strong"),
        (r"\bcredentials\b", "weak"),
        (r"\bauthorization\b", "weak"),
        (r"\bbearer\b", "weak"),
        (r"\bsecret\b", "weak"),
        (r"\btoken\b", "weak"),
    ],
    "telemetry": [
        (r"\btelemetry\b", "strong"),
        (r"\banalytics\b", "weak"),
        (r"\bmetrics\b", "weak"),
        (r"\bsentry\b", "weak"),
        (r"\bposthog\b", "weak"),
        (r"\bsegment\b", "weak"),
        (r"\bamplitude\b", "weak"),
        (r"\bmixpanel\b", "weak"),
        (r"\bdatadog\b", "weak"),
    ],
}

COMPILED_RULES = {
    category: [(re.compile(pattern, re.I | re.M), strength) for pattern, strength in patterns]
    for category, patterns in RULES.items()
}

SNAPSHOT_NEGATIVE_CONTEXT = [
    re.compile(p, re.I | re.M)
    for p in (
        r"snapshot\.status",
        r"snapshot\.generation",
        r"snapshot\.scopes?",
        r"snapshot\.expiresAt",
        r"\bgetStatus\s*\(",
        r"\bbrokerStatus\s*\(",
        r"\bauthProvider\b",
        r"\bauthentication\b",
    )
]

COMBINATION_RULES = [
    (
        {"enumeration", "snapshot", "upload"},
        "HIGH",
        "snapshot-upload",
        "Broad workspace snapshot + upload logic in a correlated code region",
        "Review whether the code can package more than the minimum prompt context and whether the user explicitly opts in.",
    ),
    (
        {"snapshot", "crypto", "upload"},
        "HIGH",
        "encrypted-upload",
        "Encrypted snapshot + upload pipeline in a correlated code region",
        "Verify key ownership, retention, deletion controls, destination, and explicit user consent.",
    ),
    (
        {"snapshot", "retry_queue", "upload"},
        "HIGH",
        "retry-upload",
        "Snapshot upload with pending/retry semantics in a correlated code region",
        "Inspect pending queues and ensure failed transfers cannot retry indefinitely without visible user control.",
    ),
    (
        {"object_storage", "upload", "snapshot"},
        "HIGH",
        "cloud-upload",
        "Workspace snapshot appears to target object storage",
        "Confirm destination account/region, retention, and whether whole-workspace upload is necessary.",
    ),
    (
        {"sensitive_mentions", "snapshot", "upload"},
        "CRITICAL",
        "sensitive-upload",
        "Sensitive-file indicators occur in a correlated snapshot/upload code path",
        "Treat as potential secret/code exfiltration until scope and exclusions are proven.",
    ),
    (
        {"enumeration", "sensitive_mentions", "archive", "upload"},
        "CRITICAL",
        "archive-exfil",
        "Recursive collection + sensitive content + archive + upload indicators occur nearby",
        "Perform a controlled canary test and packet/process trace before trusting the tool with real repositories.",
    ),
    (
        {"telemetry", "sensitive_mentions", "upload"},
        "HIGH",
        "telemetry-sensitive",
        "Telemetry/upload code references sensitive material in a correlated code region",
        "Verify telemetry payload schemas and disable data collection by default for code/secrets.",
    ),
]

SECRET_VALUE_PATTERNS = [
    ("OpenAI-style key", re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b")),
    ("GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}\b")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("Google API key", re.compile(r"\bAIza[0-9A-Za-z_-]{30,}\b")),
    ("Bearer/JWT", re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{8,}\b")),
    ("Private key header", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
]
